### PR TITLE
feat: Adds support for authenticating via service account

### LINKED ISSUE #151: Support authenticating via GOOGLE_APPLICATION_CREDENTIALS
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Command

flutterfire

### Description

Firebase CLI supports providing a service account file for authentication. It would be great for flutterfire to expose this option too.

https://stackoverflow.com/questions/59053919/login-to-firebase-using-gcloud-service-account

### Reasoning

It's an alternative more secure way of authenticating.

### Additional context and comments

_No response_

### PR DESCRIPTION
**Pull request by josh-burton**
## Description

Fixes #151

Supports passing a path to a google service account file which is used for authentication

## Type of Change

- [x ] ✨ `feat` -- New feature (non-breaking change which adds functionality)
- [ ] 🛠️ `fix` -- Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ `!` -- Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 `refactor` -- Code refactor
- [ ] ✅ `ci` -- Build configuration change
- [ ] 📝 `docs` -- Documentation
- [ ] 🗑️ `chore` -- Chore

### CODE REVIEW

**Comment by josh-burton** [comment]
@russellwheatley Are you able to approve the workflow? Does this PR sound like something you'd be interested in merging?

**Review by Salakar — APPROVED** [review]

**Review by russellwheatley — CHANGES_REQUESTED** [review]

**Comment by simply-alliv** [comment]
Hwllo guys. I appreciate the work you guys do on this CLI, butI am also curious to know what the ETA is on this as we have some CI workloads that would benefit from this feature?

The current state of the CLI causes the program to sometimes fail due to authentication. I have a service account that would probably allow me to solve the authentication issue by using it in the Flutter fire CLI.

Thanks

**Review by russellwheatley — APPROVED** [review]

**Comment by russellwheatley** [comment]
Hey @josh-burton, the next release isn't for at least a couple of weeks, so I will investigate if CI failure is occurring as a result of PR which I suspect it is before merging.

**Comment by josh-burton** [comment]
> Hey @josh-burton, the next release isn't for at least a couple of weeks, so I will investigate if CI failure is occurring as a result of PR which I suspect it is before merging.

Thank you!

**Comment by russellwheatley** [comment]
@josh-burton - do you mind fixing merge conflict and merging with latest on main? I think the tests ought to pass now 👍. Thanks!

**Comment by josh-burton** [comment]
> @josh-burton - do you mind fixing merge conflict and merging with latest on main? I think the tests ought to pass now 👍. Thanks!

Sure, rebased now.

**Comment by russellwheatley** [comment]
@josh-burton - I was trying to figure out why this was failing CI 🤔 . I realised secrets are not available for forked pull requests. I've ran locally and it works fine. Thanks once again 🎉

**Comment by josh-burton** [comment]
> @josh-burton - I was trying to figure out why this was failing CI 🤔 . I realised secrets are not available for forked pull requests. I've ran locally and it works fine. Thanks once again 🎉

thanks for merging :)

**Comment by artemsorochan** [comment]
Thanks for this feature! It would be good to add any notes on this to docs. For example, what is the minimal required role for service account for `configure` command?

**Pull request merged**
