### PR TITLE
fix: Support spaces in paths and product name for apple apps

### PR DESCRIPTION
**Pull request by AhmedLSayed9**
## Description

If the the app's directory contains space i.e: `/Users/Me/With Space/MyApp`, current configuration will read the path as `/Users/Me` and that will cause the configuration to fail when trying to access paths as `/Users/Me/firebase.json`.

Same issue will happen with product name, so we can't name an application with a space. (https://github.com/invertase/flutterfire_cli/issues/243)

fixes https://github.com/invertase/flutterfire_cli/issues/284

## Type of Change

- [ ] ✨ `feat` -- New feature (non-breaking change which adds functionality)
- [x] 🛠️ `fix` -- Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ `!` -- Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 `refactor` -- Code refactor
- [ ] ✅ `ci` -- Build configuration change
- [ ] 📝 `docs` -- Documentation
- [ ] 🗑️ `chore` -- Chore

### CODE REVIEW

**Comment by AhmedLSayed9** [comment]
@russellwheatley 
Can you check now?

**Comment by russellwheatley** [comment]
@AhmedLSayed9 - it isn't going to work, the script now sees those Xcode env variables as Dart variables.

**Comment by AhmedLSayed9** [comment]
> @AhmedLSayed9 - it isn't going to work, the script now sees those Xcode env variables as Dart variables. Look at the results of the CI run for more information.

My bad, I had to escape the '$'. I've fixed them now.

**Comment by russellwheatley** [comment]
@AhmedLSayed9 - could you write a test like this: https://github.com/invertase/flutterfire_cli/blob/main/packages/flutterfire_cli/test/configure_test.dart#L342-L379

Except change the applePath to one with spaces in it and create a different one for macOS and iOS. Just select platforms as iOS and macOS in the flutterfire configure command and remove checks unrelated to apple platforms.

**Comment by AhmedLSayed9** [comment]
@russellwheatley 
Thanks for the tips. I've added a test case.

**Comment by AhmedLSayed9** [comment]
This should also fix #243.

@russellwheatley Can you check if there's still something to add?

**Comment by russellwheatley** [comment]
@AhmedLSayed9 - thanks for the PR. CI won't run correctly for contributor pull requests. I just tested this locally and it was successful:
Screenshot 2024-04-18 at 11 34 29

Good work 💪

**Comment by rahulraj-idt** [comment]
@russellwheatley This fixes a critical error, shall we have a release for this ? I also faced the same issue.

**Comment by russellwheatley** [comment]
@rahulraj-idt - This has come out in a dev release: https://github.com/invertase/flutterfire_cli/blob/main/CHANGELOG.md#flutterfire_cli---v101-dev0

**Pull request merged**
