### PR TITLE
refactor(hooks): remove deprecated templating

### PR DESCRIPTION
**Pull request by felangel**
## Description

- refactor(hooks): remove deprecated templating

## Type of Change

- [ ] ✨ `feat` -- New feature (non-breaking change which adds functionality)
- [ ] 🛠️ `fix` -- Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ `!` -- Breaking change (fix or feature that would cause existing functionality to change)
- [X] 🧹 `refactor` -- Code refactor
- [ ] ✅ `ci` -- Build configuration change
- [ ] 📝 `docs` -- Documentation
- [ ] 🗑️ `chore` -- Chore

### CODE REVIEW

**Comment by felangel** [comment]
@Lyokone let me know if you have any questions. It'd be great if you could review and publish these updates in order to preserve backward compatibility, thanks! 🙏

**Review by Lyokone — APPROVED** [review]

**Comment by Lyokone** [comment]
@felangel Thanks for the patch, LGTM :)

**Comment by felangel** [comment]
@Lyokone thanks for merging! Do you have an eta on when the update will be published? Thanks 🙏

**Comment by Lyokone** [comment]
Hello @felangel, It's been published :)

**Pull request merged**
