### PR TITLE
chore: updated http dependency range

### LINKED ISSUE #255: request:  Upgrade http dependency to match ^1.0.0
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Command

My project use http: ^1.0.0
```dart
flutter install
``` 

### Description

flutterfire_cli ^0.3.0-dev.19 requires http ^0.13.5

### Reasoning

Would like to add this package as project dev dependency.

### Additional context and comments

_No response_

### PR DESCRIPTION
**Pull request by OutdatedGuy**
## Description

Updates the `http` package range to allow `>= 1.0.0 <2.0.0`. A version range is necessary as current `pub_updater` depends on `http: ^0.13.5`.

resolves #255

Will follow-up with 2 more PRs to update `pub_updater` and then change `http` version to `^1.2.1`.

## Type of Change

- [ ] ✨ `feat` -- New feature (non-breaking change which adds functionality)
- [ ] 🛠️ `fix` -- Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ `!` -- Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 `refactor` -- Code refactor
- [ ] ✅ `ci` -- Build configuration change
- [ ] 📝 `docs` -- Documentation
- [x] 🗑️ `chore` -- Chore

### CODE REVIEW

**Comment by russellwheatley** [comment]
@OutdatedGuy - thanks for this, I'm running CI. I'll merge provided it is successful 👍

**Comment by OutdatedGuy** [comment]
Why are the tests failing @russellwheatley? Anything I need to fix?

**Comment by russellwheatley** [comment]
Running FFCLI tests requires being a member of Invertase org, but I can run locally. Everything seems fine to me.

**Review by russellwheatley — APPROVED** [review]

**Comment by russellwheatley** [comment]
@OutdatedGuy - if you want to follow up with further PRs I'll be happy to check them out 👍

**Pull request merged**
