### PR TITLE
ci: Use GitHub actions

### PR DESCRIPTION
**Pull request by spydon**
## Description

This makes use of GitHub actions for the pipeline instead of separate scripts for each platform.

## Type of Change

- [x] ✅ `ci` -- Build configuration change

### CODE REVIEW

**Review by Salakar — APPROVED** [review]
🎉

**Comment by blaugold** [comment]
Handling of error code 183 has been added in `pub` but is not in stable yet.
This is the commit which rolled the fix into the Dart SDK repo: https://github.com/dart-lang/sdk/commit/2aa637afce62adeba7a70310a6577160bcb6d776

**Comment by spydon** [comment]
> Handling of error code 183 has been added in `pub` but is not in stable yet.
> This is the commit which rolled the fix into the Dart SDK repo: https://github.com/dart-lang/sdk/commit/2aa637afce62adeba7a70310a6577160bcb6d776

That's great, do you know if this was included in Dart 2.17.5?

**Comment by blaugold** [comment]
> That's great, do you know if this was included in Dart 2.17.5?

I don't think so, unfortunately. Looks like this will land in 2.18.0.

**Comment by spydon** [comment]
> I don't think so, unfortunately. Looks like this will land in 2.18.0.

Ah too bad. How do you know when different commits will be released?

**Comment by blaugold** [comment]
I noticed that this specific commit adds to the changelog for 2.18.0 :)

**Comment by spydon** [comment]
Since Dart 2.18.0 now is released, can we try re-running this? :)

**Review by Lyokone — COMMENTED** [review]
I see the Windows test isn't passing 🤔 But I cannot relaunch the CI, maybe @russellwheatley ?

**Comment by spydon** [comment]
> I see the Windows test isn't passing 🤔 But I cannot relaunch the CI, maybe @russellwheatley ?

Pushed an empty commit to force a re-run, but I forgot that the workflows require approval since I haven't had any PRs merged in this repo before. 😅

**Comment by Lyokone** [comment]
Should be good 👍

**Review by Lyokone — APPROVED** [review]

**Pull request merged**
